import type { Layer2D } from '../types/slicer';
import { extrusionDelta, segmentLength } from './extrusion';
import type { GCodeGenerator, GCodeGeneratorContext } from './types';

const PAUSE_Z_TOLERANCE = 0.05;

function formatNum(n: number, digits = 3): string {
  return n.toFixed(digits);
}

/**
 * Standard FDM G-code for Prusa MK4 (M104/M109, M140/M190, G1 perimeters).
 */
export class PrusaMk4GCodeGenerator implements GCodeGenerator {
  readonly id = 'prusa-mk4';
  readonly label = 'Prusa MK4 (FDM)';

  generate(context: GCodeGeneratorContext): string {
    const { settings, slice } = context;
    const lines: string[] = [];

    lines.push('; Generated by 3d-slicer — Prusa MK4');
    lines.push('M104 S' + settings.printTemperature + ' ; set nozzle temp');
    lines.push('M140 S' + settings.bedTemperature + ' ; set bed temp');
    lines.push('G28 ; home all axes');
    lines.push('G90 ; absolute positioning');
    lines.push('M83 ; relative extrusion');
    lines.push('G92 E0 ; reset extruder');
    lines.push('M109 S' + settings.printTemperature + ' ; wait nozzle');
    lines.push('M190 S' + settings.bedTemperature + ' ; wait bed');

    let firstLayer = true;

    for (const layer of slice.layers) {
      this.emitLayer(lines, layer, settings, firstLayer);

      if (
        settings.pauseAtZ > 0 &&
        Math.abs(layer.z - settings.pauseAtZ) <= PAUSE_Z_TOLERANCE
      ) {
        lines.push('; Pause at Z=' + formatNum(layer.z));
        lines.push('M600 ; filament change / pause print');
      }

      firstLayer = false;
    }

    lines.push('M104 S0 ; nozzle off');
    lines.push('M140 S0 ; bed off');
    lines.push('G28 X0 Y0 ; park');
    lines.push('M84 ; disable motors');
    lines.push('; End of print');

    return lines.join('\n') + '\n';
  }

  private emitLayer(
    lines: string[],
    layer: Layer2D,
    settings: GCodeGeneratorContext['settings'],
    firstLayer: boolean,
  ): void {
    const speed = firstLayer ? settings.firstLayerSpeed : settings.printSpeed;
    const travel = settings.travelSpeed;

    lines.push('');
    lines.push(';LAYER:' + formatNum(layer.z));
    lines.push('G0 Z' + formatNum(layer.z) + ' F' + travel * 60);

    for (const contour of layer.contours) {
      if (contour.points.length < 2) continue;

      const pts = contour.points;
      const closed = contour.closed && pts.length >= 2;

      const start = pts[0]!;
      lines.push(
        'G0 X' +
          formatNum(start.x) +
          ' Y' +
          formatNum(start.y) +
          ' F' +
          travel * 60,
      );

      const pointCount = closed ? pts.length + 1 : pts.length;
      for (let i = 1; i < pointCount; i++) {
        const prev = pts[i - 1]!;
        const curr = i < pts.length ? pts[i]! : pts[0]!;
        const len = segmentLength(prev, curr);
        const dE = extrusionDelta(
          len,
          layer.layerHeight,
          settings.lineWidth,
          settings.filamentDiameter,
        );
        lines.push(
          'G1 X' +
            formatNum(curr.x) +
            ' Y' +
            formatNum(curr.y) +
            ' E' +
            formatNum(dE, 5) +
            ' F' +
            speed * 60,
        );
      }
    }
  }
}

export const prusaMk4Generator = new PrusaMk4GCodeGenerator();
